# ~/.config/starship.toml

format = "$directory $git_branch $character"

[directory]
truncation_length = 3

# [git_branch]
symbol = "🌱 "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
